[project]
name = "odoo-addons-oca-report-print-send"
version = "18.0.20250120.0"
dependencies = [
    "odoo-addon-base_report_to_printer==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
